version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my_python_app:latest
    stdin_open: true
    tty: true
    command: sh -c "python main.py"
    environment:
      - API_BASE_URL=${API_BASE_URL}
  server:
    build:
      context: ./server 
      dockerfile: Dockerfile
    container_name: my_flask_app_container
    image: my_flask_app:latest
    ports:
      - "3001:8000"
    environment:
      - DATA_BACKEND=redis
      # - DATA_BACKEND=mysql
    depends_on:
      - redis
      # - mysql
    command: ["gunicorn", "server:app", "-b", "0.0.0.0:8000", "-w", "4"]

  redis:
    image: "redis:latest"
  # mysql:
  #   image: "mysql:latest"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password123
  #     MYSQL_DATABASE: my_wishes_db
  #   volumes:
  #     - ~/my_wishes_db:/var/lib/mysql 
