version: "3"
services:
  api:
    build: .
    ports:
      - "3001:8000"
    depends_on:
      - redis
    command: ["gunicorn", "server:app", "-b", "0.0.0.0:8000", "-w", "4"]
  redis:
    image: "redis:latest"
