version: "3"
services:
  api:
    build: .
    container_name: my_flask_app_container
    image: my_flask_app:latest
    ports:
      - "3001:8000"
    environment:
      - DATA_BACKEND=redis
      # - DATA_BACKEND=mysql
    depends_on:
      - redis
      # - mysql
    command: ["gunicorn", "server:app", "-b", "0.0.0.0:8000", "--access-logfile", "-", "-w", "4"]
  redis:
    image: "redis:latest"
  # mysql:
  #   image: "mysql:latest"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password123
  #     MYSQL_DATABASE: my_wishes_db
  #   volumes:
  #     - ~/my_wishes_db:/var/lib/mysql 
